
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#       url: jdbc:mysql://39.101.135.227:32769/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
      url: jdbc:mysql://39.101.135.227:32769/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:

    hibernate:
      ddl-auto: update
    #显示sql
    show-sql: true


server:
  port: 30030
