#server:
#  port: 8080
#spring:
#  datasource:
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
#    username: root
#    password: root
#  jpa:
#    show-sql: true # 默认false，在日志里显示执行的sql语句
#    database: mysql
#    hibernate.ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
#    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl #指定jpa的自动表生成策略，驼峰自动映射为下划线格式
#        #physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://30.98.170.203:30306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:

    hibernate:
      ddl-auto: update
    #显示sql
    show-sql: true


server:
  port: 30030
